############################
## CHANGE THESE
############################

baseURL: "https://gustavo-leon-lenio.github.io/qubt-template"
title: qubt-template

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
